# This is a basic workflow to help you get started with Actions

name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'
      # ^^^ not sure, which pkgs are necessary...
    - name: Testing tkinter import
      run: main.py
