# This is a basic workflow to help you get started with Actions

name: Python application

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Testing tkinter import
      run: main.py
